name: example to use override entrypoint for service image

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    sevices:
      mysql:
        image: mysql:8.0
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          -e MYSQL_ROOT_PASSWORD=password
          -e MYSQL_DATABASE=sandbox
          --entrypoint sh mysql:8.0 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    steps:
    - run: |
        mysql -h mysql --port 3306 -uroot -ppassword -e "SHOW DATABASES"
        mysql -h mysql --port 3306 -uroot -ppassword -e "STATUS"

